<a href="https://colab.research.google.com/github/urchbee/Numpy-and-Pandas/blob/main/Numpy_x_Pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

1. Create a nested list which contains the name, age and race of 10 people each. Turn this list to a dataframe.

In [2]:
#creating dataframe from a nested list
personal_info = [["Sandra", 30, "Black"], ["Gong Yoo", 44, "Caucasian"], 
                ["Melanie", 33, "White"], ["Seo Joon", 32, "Caucasian"], 
                ["Frances", 37, "Black"],["Eugene", 36, "Black"],
                ["Jessi", 34, "Caucasian"], ["Mary", 27, "White"],
                ["Stephanie", 22, "Black"], ["Dominic", 19, "White"]]
revised_info = pd.DataFrame(personal_info)
revised_info

0   1          2
0     Sandra  30      Black
1   Gong Yoo  44  Caucasian
2    Melanie  33      White
3   Seo Joon  32  Caucasian
4    Frances  37      Black
5     Eugene  36      Black
6      Jessi  34  Caucasian
7       Mary  27      White
8  Stephanie  22      Black
9    Dominic  19      White

2. Label the columns with the appropriate column names

In [3]:
#changing column names in revised_info 
revised_info.columns = ["Name", "Age", "Race"]
revised_info


Name  Age       Race
0     Sandra   30      Black
1   Gong Yoo   44  Caucasian
2    Melanie   33      White
3   Seo Joon   32  Caucasian
4    Frances   37      Black
5     Eugene   36      Black
6      Jessi   34  Caucasian
7       Mary   27      White
8  Stephanie   22      Black
9    Dominic   19      White

3. Add a new column to your dataframe called weight and enter values for it.

In [4]:
#adding another column to revised_info data above
revised_info["Weight"] = [55, 80 , 50 , 65 , 50 , 75 , 45 , 70 , 85 , 90]
revised_info

Name  Age       Race  Weight
0     Sandra   30      Black      55
1   Gong Yoo   44  Caucasian      80
2    Melanie   33      White      50
3   Seo Joon   32  Caucasian      65
4    Frances   37      Black      50
5     Eugene   36      Black      75
6      Jessi   34  Caucasian      45
7       Mary   27      White      70
8  Stephanie   22      Black      85
9    Dominic   19      White      90

4. Change the name of the column for "weight" to "height". Feel free to use any method you find. 

In [5]:
#changing the column name from weight to height using .rename method
revised_data = revised_info.rename(columns={"Weight" : "Height"})
revised_data


Name  Age       Race  Height
0     Sandra   30      Black      55
1   Gong Yoo   44  Caucasian      80
2    Melanie   33      White      50
3   Seo Joon   32  Caucasian      65
4    Frances   37      Black      50
5     Eugene   36      Black      75
6      Jessi   34  Caucasian      45
7       Mary   27      White      70
8  Stephanie   22      Black      85
9    Dominic   19      White      90

5. Change the row index to another indexing of your choice.

In [6]:
#changing row index starting from 1 instead of 0
revised_data.index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
revised_data

Name  Age       Race  Height
1      Sandra   30      Black      55
2    Gong Yoo   44  Caucasian      80
3     Melanie   33      White      50
4    Seo Joon   32  Caucasian      65
5     Frances   37      Black      50
6      Eugene   36      Black      75
7       Jessi   34  Caucasian      45
8        Mary   27      White      70
9   Stephanie   22      Black      85
10    Dominic   19      White      90

6. Select/display only the age and race columns

In [8]:
#displaying age and race columns by slicing using the .iloc method
#iloc method is primarily for integer based indexing. 
#iloc[row slicing, column slicing]

revised_data.iloc[0:10, 1:3]

Age       Race
1    30      Black
2    44  Caucasian
3    33      White
4    32  Caucasian
5    37      Black
6    36      Black
7    34  Caucasian
8    27      White
9    22      Black
10   19      White

7. Select/display the first five names and their age 

In [9]:
#showing the first 5 names and their age using same iloc method as above
#slicing using .iloc(row slice, column slice)
revised_data.iloc[0:5, 0:2]


Name  Age
1    Sandra   30
2  Gong Yoo   44
3   Melanie   33
4  Seo Joon   32
5   Frances   37

8. Select all rows but only the third column

In [10]:
#display all rows in the 3rd column which is "Race"
#using same iloc method slice the positions before the 3rd column
revised_data.iloc[0:10, 2:3]


Race
1       Black
2   Caucasian
3       White
4   Caucasian
5       Black
6       Black
7   Caucasian
8       White
9       Black
10      White

9. Write some code to return the row index back to the default numbering before it was changed. Use your researching skills.

In [11]:
#changing row index to default indexing starting from 0
#resetting the row index using .reset_index(drop=True) method
#.reset_index() adds the current row index as a new "index" column in DF, the (drop=True) does not add the new column of the current row index
revised_info.reset_index(drop=True)


Name  Age       Race  Weight
0     Sandra   30      Black      55
1   Gong Yoo   44  Caucasian      80
2    Melanie   33      White      50
3   Seo Joon   32  Caucasian      65
4    Frances   37      Black      50
5     Eugene   36      Black      75
6      Jessi   34  Caucasian      45
7       Mary   27      White      70
8  Stephanie   22      Black      85
9    Dominic   19      White      90

In [12]:
chimamanda = {"Books":["Americanah", "Half of a Yellow Sun", "Purple Hibiscus",
                    "The Thing Around Your Neck", "We Should All Be Feminists"], 
             "Ratings":[297972, 120131, 5116, 32064, 204882]}

10. Create a dataframe from the dictionary above. Using the dataframe, select books with ratings not less than 200000

In [13]:
#create a dataframe from the dictionary
Novels = pd.DataFrame(chimamanda)
Novels

Books  Ratings
0                  Americanah   297972
1        Half of a Yellow Sun   120131
2             Purple Hibiscus     5116
3  The Thing Around Your Neck    32064
4  We Should All Be Feminists   204882

In [14]:
#print out books with ratings not less than 200000
Novels[Novels.Ratings >= 200000]





Books  Ratings
0                  Americanah   297972
4  We Should All Be Feminists   204882

In [15]:
import numpy as np

11. Create a numpy array with data type boolean

In [16]:
#creating a boolean data type array
#using .array method and boolean true or false values
arr = np.array([False, True, False, True, True, False])
print(arr)

[False  True False  True  True False]


In [17]:
# 12. Convert the following array to an integer

a = np.array([[True, False, False],
              [True, True, True],
              [False, False, False]])

p = a.astype(int)

print(p)

[[1 0 0]
 [1 1 1]
 [0 0 0]]


In [18]:
#13. Stack these numpy arrays - vertically and horizontally
# using hstack method to stack the rows horizontally

a = np.array([[7, 8, 9],
              [10, 11, 12]])

aa = np.array([[1, 2, 3],
               [4, 5, 6]])

arow = np.hstack((a, aa))
print(arow)


[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


In [19]:
#using vstack method to stack the columns vertically
acolumn = np.vstack((a, aa))
print(acolumn)

[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


14. Create 2 3D arrays, add them together to create a new array, then sort the new array.

In [20]:
#creating 2 individual 3D arrays and joining together
arr1 = np.array([[[0, 3, 1], [1, 5, 3]], [[4, 7, 6], [3, 2, 6]]])
arr2 = np.array([[[5, 2, 3], [3, 0, 9]], [[9, 10, 8], [7, 9, 4]]])

#using hstack method to join the rows 
arr3 = np.hstack((arr1, arr2))
print(arr3)




[[[ 0  3  1]
  [ 1  5  3]
  [ 5  2  3]
  [ 3  0  9]]

 [[ 4  7  6]
  [ 3  2  6]
  [ 9 10  8]
  [ 7  9  4]]]


In [21]:
#sorting array output above to put elements in ordered sequence
#using .sort method prints out in sequential order
print(np.sort(arr3))

[[[ 0  1  3]
  [ 1  3  5]
  [ 2  3  5]
  [ 0  3  9]]

 [[ 4  6  7]
  [ 2  3  6]
  [ 8  9 10]
  [ 4  7  9]]]


In [22]:
#15. Using step slicing, slice the array below from any position using 3 steps
#step slicing: this is used to determine the step of the slicing. 
#1 element where you want the argument to start 
#2nd element where to stop 
#3rd element is how many steps to skip, here it is 3 steps

a = np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])
print(a[2:6:3])


[7 9]
